[deps]
ACE1 = "e3f9bc04-086e-409a-ba78-e9769fe067bb"
ACE1pack = "8c4e8d19-0bd6-4234-8309-7210652e3178"
ACE1x = "5cc4c08c-8782-4a30-af6d-550b302e9707"
AtomsBase = "a963bdd2-2df7-4f54-a1ee-49d51e6be12a"
InteratomicBasisPotentials = "37c59853-c2ad-4e3a-930c-a41b2395fb19"
InteratomicPotentials = "a9efe35a-c65d-452d-b8a8-82646cd5cb04"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JuLIP = "945c410c-986d-556a-acb1-167a618e0462"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PotentialLearning = "82b0a93c-c2e3-44bc-a418-f0f89b0ae5c2"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAtomic = "a7773ee8-282e-5fa2-be4e-bd808c38a91a"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
